### ISSUE TITLE
bug: backend: search custom property data by book id and user id

### ISSUE THREAD

**Issue by kaleykwan** [Purdue-CS307-tsundoku/tsundoku#108]
### What happened?

I need to be able to search custom property data by book id and user id so I can show them on the full review page, which shows the star rating, text review, and custom properties. 

### What can we do to reproduce the problem?

n/a

**Comment by ericswpark** [comment]
@kaleykwan the `user_id` search is not necessary since users can only view their own private data, so that's already filtered
