### ISSUE TITLE
bug: mobile: Wrapped not working

### ISSUE THREAD

**Issue by ericswpark** [Purdue-CS307-tsundoku/tsundoku#190]
### What happened?

The Wrapped functionality loads indefinitely, with "Loading Wrapped" and a spinner.

### What can we do to reproduce the problem?

1. Navigate to Discover
2. Click on Wrapped banner
3. (optional) accept any permissions prompts
4. See result

**Comment by sliu-1** [comment]
Fixed. There was an undefined parameter while trying to save to database.
